server:
  port: 8080
  servlet:
    context-path: /orgmanager

spring:
  application:
    name: caller-service
  config:
    import: optional:configserver:http://config-server:8888

called-service:
  url: https://called-web:8443/soa/api/v1

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: caller-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh
