server:
  port: 8080
  servlet:
    context-path: /orgmanager

spring:
  application:
    name: rest-adapter
  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: false

soap-caller:
  url: http://soap-caller:8080/soap/CallerService

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: rest-adapter

ribbon:
  eureka:
    enabled: true
  ConnectTimeout: 5000
  ReadTimeout: 60000

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh
