server:
  port: 8080

spring:
  application:
    name: zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: zuul-gateway

zuul:
  routes:
    caller-service:
      path: /orgmanager/**
      serviceId: caller-service
      strip-prefix: false
  ribbon-isolation-strategy: thread

ribbon:
  eureka:
    enabled: true
  ConnectTimeout: 5000
  ReadTimeout: 60000

management:
  endpoints:
    web:
      exposure:
        include: health,info,routes
