server:
  port: 8080

spring:
  application:
    name: caller-service

called-service:
  url: https://called-web:8443/soa/api/v1

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
